// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookingController from "./booking_controller"
application.register("booking", BookingController)

import BookingTypeController from "./booking_type_controller"
application.register("booking_type", BookingTypeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
